// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace StudentRegistration.Entity
{
    public partial class login
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Uname { get; set; }
        [Required]
        [StringLength(16)]
        public string Upassword { get; set; }
    }
}