// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace StudentRegistration.Entity
{
    public partial class StudentRegistrationEntity : DbContext
    {
        public StudentRegistrationEntity()
        {
        }

        public StudentRegistrationEntity(DbContextOptions<StudentRegistrationEntity> options)
            : base(options)
        {
        }

        public virtual DbSet<StudentDetails> StudentDetails { get; set; }
        public virtual DbSet<login> login { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
//#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=Freasher2021;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<StudentDetails>(entity =>
            {
                entity.HasKey(e => e.Student_Id)
                    .HasName("PK__StudentD__A2F4E98C945F0BDA");

                entity.Property(e => e.Created_Time_Stamp).HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Favorite_Subject).IsUnicode(false);

                entity.Property(e => e.Fisrt_Name).IsUnicode(false);

                entity.Property(e => e.Interested_Course).IsUnicode(false);

                entity.Property(e => e.Last_Name).IsUnicode(false);

                entity.Property(e => e.Updated_Time_Stamp).HasDefaultValueSql("(getdate())");
            });

            modelBuilder.Entity<login>(entity =>
            {
                entity.Property(e => e.Uname).IsUnicode(false);

                entity.Property(e => e.Upassword).IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}